version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pathfinder_elm
      MYSQL_DATABASE: pathfinder_elm
      MYSQL_USER: pathfinder_elm
      MYSQL_PASSWORD: pathfinder_elm
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306

  adminer:
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - 8080:8080

  backend:
    depends_on:
      - db
    build:
      context: .
      dockerfile: backend.Dockerfile
    volumes:
      - .:/work
      - ./backend/config-dev.json:/work/backend/config.json
    working_dir: /work
    ports:
      - 5000:80

  dev:
    depends_on:
      - backend
    build:
      context: .
      dockerfile: dev.Dockerfile
    entrypoint: scripts/entrypoint
    volumes:
      - .:/work
      - elm-stuff-cache:/work/elm-stuff
      - node-modules-cache:/work/node_modules
      - root-cache-cache:/root/.cache
      - root-elm-cache:/root/.elm
    working_dir: /work
    ports:
      - 8000:8000

volumes:
  db-data: ~
  elm-stuff-cache: ~
  node-modules-cache: ~
  root-cache-cache: ~
  root-elm-cache: ~
