#!/bin/bash

set -Eeuo pipefail

cd "$(dirname "$0")/.."

export PATH=node_modules/.bin:$PATH

# For CI - in dev, instead use: ./scripts/setup
command -v elm >/dev/null || npm install -g elm

rm -rf dist
mkdir dist
cp -r assets src/index.html dist
elm make src/Main.elm --output=dist/elm.js
