#!/bin/bash

set -Eeuo pipefail

cd "$(dirname "$0")/.."

command -v elm >/dev/null || npm install -g elm

rm -rf dist
mkdir dist
cp -r assets src/index.html dist
elm make src/Main.elm --output=dist/elm.js
