#!/bin/bash

set -Eeuo pipefail

cd "$(dirname "$0")/.."

export PATH=node_modules/.bin:$PATH

set -x

env | grep -i NPM_CONFIG_PREFIX

command -v elm-format || {
  # Need to manually import GPG keys for developer of elm-format
  curl -s https://keybase.io/avh4/pgp_keys.asc | gpg --import

  yay -S elm-format-bin
}

command -v elm || yay -S elm-platform-bin

command -v npm || yarn global add npm || yay -S npm

npm install

{ echo "Setup complete! =)"; } 2> /dev/null
