#!/bin/bash

set -Eeuo pipefail

cd "$(dirname "$0")/.."

export PATH=node_modules/.bin:$PATH

printf "Generating elm.json... "
jq '.["source-directories"] += ["../src"] | .dependencies.direct["brian-watkins/elm-spec"] = "3.1.0"' --indent 4 < elm.json > spec/elm.json
echo "done"

set -x

elm-spec --specRoot=spec
