#!/bin/bash

set -Eeuo pipefail

cd "$(dirname "$0")/.."

export PATH=node_modules/.bin:$PATH

printf "Generating elm.json... "

ruby -r json -e '
  elm = JSON.load_file("elm.json")
  elm["source-directories"] << "../src"
  elm["dependencies"]["direct"]["brian-watkins/elm-spec"] = "3.1.0"
  File.write("spec/elm.json", JSON.pretty_generate(elm, indent: " " * 4) + "\n")
  puts "done"
'

elm-spec --specRoot=spec
